version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start:api
    container_name: chat-api
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "3003:3003"
    networks:
      - chat-network
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy


  realtime:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start:realtime
    ports:
      - "3002:3002"
    env_file:
      - .env
    networks:
      - chat-network
    restart: unless-stopped
    depends_on:
      rabbitmq:
        condition: service_healthy

  haproxy:
    image: haproxy:3.2-alpine
    container_name: chat-proxy
    ports:
      - "80:80"
      - "8404:8404"
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - api
      - realtime
    networks:
      - chat-network
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: chat-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - chat-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  postgres:
    image: postgres:16-alpine
    container_name: chat-postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}

    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - chat-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  rabbitmq_data:
  postgres_data:

networks:
  chat-network:
    driver: bridge
